
server:
  port: 8082

spring:
  application:
    name:
      payment-service
  datasource:
    url: jdbc:postgresql://my-postgres:5433/payments
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create

  cache:
    type: redis

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379
