server:
  port: 8081

spring:
  application:
    name: installment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/installments
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    bootstrap-servers: localhost:9092
