pipeline {
    agent any

    environment {
        IMAGE_NAME = 'babyaltushka/payment-service'
        DOCKERHUB_CREDENTIALS = 'dockerhub-creds'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build with Gradle') {
            steps {
                dir('payment-service') {
                    sh './gradlew clean build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('payment-service') {
                    script {
                        docker.build("${IMAGE_NAME}")
                    }
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKERHUB_CREDENTIALS}") {
                        docker.image("${IMAGE_NAME}").push('latest')
                    }
                }
            }
        }
    }

    post {
        success {
            echo '✅ payment-service построен и загружен в Docker Hub'
        }
        failure {
            echo '❌ Ошибка при сборке payment-service'
        }
    }
}
