pipeline {
    agent any

    environment {
        IMAGE_NAME = 'babyaltushka/payment-service'
        DOCKERHUB_CREDENTIALS = 'dockerhub-creds'
    }

    stages {
        stage('Checkout') {
            steps {
                sshagent(['git-creds']) {
                      sh 'mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts'
                      sh 'ssh -T git@github.com || true'
                      checkout scm
                    }
            }
        }

        stage('Build with Gradle') {
            steps {
                dir('payment-service') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('payment-service') {
                    script {
                        docker.build("${IMAGE_NAME}")
                    }
                }
            }
        }

        stage('Check Docker') {
            steps {
                sh 'docker --version'
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKERHUB_CREDENTIALS}") {
                        docker.image("${IMAGE_NAME}").push('latest')
                    }
                }
            }
        }
    }

    post {
        success {
            echo '✅ payment-service построен и загружен в Docker Hub'
        }
        failure {
            echo '❌ Ошибка при сборке payment-service'
        }
    }
}
