server:
  port: 8080

spring:
  application:
    name:
      user-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: installment-service
            uri: http://localhost:8081
            predicates:
              - Path=/installments/**
          - id: payment-service
            uri: http://localhost:8082
            predicates:
              - Path=/payments/**
